/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YPdBb8ZvvCY
 */


export default function Component() {
  return (
    <div key="1" className="bg-[#5590c9] min-h-screen p-4">
      <div className="max-w-2xl mx-auto">
        <header className="flex justify-between items-center mb-4">
          <h1 className="text-3xl font-bold text-white">{"Today's Tech Reads"}</h1>
          <div className="flex gap-4">
            <button className="p-2 bg-white text-[#5590c9] rounded-md">Sign In</button>
            <button className="p-2 bg-white text-[#5590c9] rounded-md">Sign Up</button>
          </div>
        </header>
        <div className="grid gap-4">
          <div className="flex items-center justify-center space-x-2 text-2xl font-bold text-[#000000]">
            <ChevronLeftIcon className="h-4 w-4" />
            <span>2023/1/23 Tue.</span>
            <ChevronRightIcon className="h-4 w-4" />
          </div>
          <div className="bg-white rounded-lg shadow-md p-4">
            <div className="flex items-start space-x-4">
              <img
                alt="Article thumbnail"
                className="w-24 h-24 object-cover rounded-md"
                height="100"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "100/100",
                  objectFit: "cover",
                }}
                width="100"
              />
              <div className="space-y-2">
                <h2 className="text-xl font-bold text-[#5590c9]">Article Title 1</h2>
                <p className="text-gray-700">
                  This is a summary of the first article. It gives a brief overview of the content.
                </p>
              </div>
            </div>
            <div className="mt-4 p-2 bg-gray-100 rounded-md">
              <h3 className="text-lg font-semibold text-[#5590c9]">Comments</h3>
              <p className="text-gray-700">This is a comment on the first article.</p>
              <p className="text-gray-700">This is another comment on the first article.</p>
            </div>
          </div>
        </div>
        <div className="mt-4 bg-white rounded-lg shadow-md p-4">
          <form className="flex flex-col space-y-2">
            <label className="text-lg font-semibold text-[#5590c9]" htmlFor="article-url-3">
              Share an article you read today:
            </label>
            <input className="p-2 border border-gray-200 border-gray-300 rounded-md dark:border-gray-800" placeholder="Enter article URL" type="url" />
            <textarea
              className="p-2 border border-gray-200 border-gray-300 rounded-md mt-2 dark:border-gray-800"
              id="comment"
              placeholder="Enter your comment"
            />
            <button className="p-2 bg-[#5590c9] text-white rounded-md" type="submit">
              Submit
            </button>
          </form>
        </div>
      </div>
    </div>
  )
}


function ChevronLeftIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18 L9 12 L15 6" />
    </svg>
  )
}


function ChevronRightIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
